### ISSUE TITLE
Not Compatible with Latest Adobe Heartbeat Library

### ISSUE THREAD

**Issue by michaelrenda** [brightcove/brightcove-player-sdk-ios-omniture#3]
This library won't build with the latest version (1.5.5) of the Adobe Heartbeat Library.  Apparently, Adobe changed several of the header files in their library.

**Comment by timothyrodgers** [comment]
@michaelrenda The Omniture v1.1.0 plugin (a static framework) for Brightcove Player SDK for iOS was  built against of Adobe Media Services v4.11.1 and Adobe Video Heartbeat v2.0.0. The v1.1.0 plugin was released on Aug 25, 2016.
